AppGDP/urls.py
from django.urls import path
from . import views
from .views import buscar_itens

urlpatterns = [
        path('', views.homepage, name="homepage"),         # Inclui as urls do app blog
        path('homepageDark', views.homepageDark, name="homepageDark"),   # Inclui as urls do app blog
        path('login', views.login, name="login"),           # Inclui as urls do app blog
        path('cadastroUsuario', views.cadastroUsuario, name='cadastroUsuario'),
        path('profile', views.profile, name="profile"),       # Inclui as urls do app blog
        path('faq', views.faq, name="faq"),                 # Inclui as urls do app blog
        path('welcomeHomepage', views.welcomeHomepage, name="welcomeHomepage"),   # Inclui as urls do app blog
        path('itens', views.itens, name="itens"),           # Inclui as urls do app blog
        path('adicionar_inventario', views.adicionar_inventario, name="adicionar_inventario"),   # Inclui as urls do app blog
        path('buscar', buscar_itens, name='buscar_itens'), 
        path('excluir_inventario', views.excluir_inventario, name='excluir_inventario'),

]

GerenciamentoDePatrimonios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppGDP.urls')),         # Inclui as urls do app blog
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppGDP/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

    
class Senai(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.TextField(max_length=1500)
    logo = models.ImageField(upload_to='logo/')

    def __str__(self):
        return self.titulo
    
from django.db import models

class Inventario(models.Model):
    num_inventario = models.CharField(max_length=10, unique=True)
    denominacao = models.CharField(max_length=255)
    localizacao = models.CharField(max_length=10)
    link_imagem = models.URLField(max_length=500, blank=True, null=True) 
    sala = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return f"{self.num_inventario} - {self.denominacao}"

AppGDP/forms.py
from django import forms
from .models import Inventario

class formCadastroUsuario(forms.Form):
    first_name = forms.CharField(label="Nome", max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="Sobrenome", max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    user = forms.CharField(label="Usuário", max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="Email", max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Senha", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class FormLogin(forms.Form):
    user = forms.CharField(label="Usuario", max_length=40)
    password = forms.CharField(label="Senha", widget=forms.PasswordInput)

class InventarioForm(forms.ModelForm):
    class Meta:
        model = Inventario
        fields = ['num_inventario', 'denominacao', 'localizacao','sala', 'link_imagem']  

AppGDP/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from .forms import FormLogin, formCadastroUsuario, InventarioForm
from .models import Senai
from django.contrib.auth.models import User
from .models import Inventario
from django.core.cache import cache
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse

# Create your views here.

def homepage(request):
    return render(request, 'homepage.html')

def homepageDark(request):
    return render(request, 'homepageDark.html')

def login(request):
    return render(request, 'login.html')


def profile(request):
    return render(request, 'profile.html')

def faq(request):
    return render(request, 'faq.html')

def welcomeHomepage(request):
    return render(request, 'welcomeHomepage.html')

# Importar o modelo de itens (substitua Item pelo nome correto do seu modelo)


def itens(request):
    inventario = Inventario.objects.all()
    item_especifico = inventario.first()  # ou qualquer outro critério para escolher o item
   
    if request.method == 'POST':
        form = InventarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('itens')  # Redireciona para a página de itens
    else:
        form = InventarioForm()
    
    return render(request, 'itens.html', {'form': form, 'inventario': inventario, 'item_especifico': item_especifico})



def adicionar_inventario(request):
    if request.method == 'POST':
        form = InventarioForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirecionar para a rota inicial, independente de onde estava
    else:
        form = InventarioForm()
    
    # Se precisar listar todos os itens no modal de adição, inclua isso:
    inventario = Inventario.objects.all()
    
    return render(request, 'itens.html', {'form': form, 'inventario': inventario})



def cadastroUsuario(request):
    context = {}
    dadosSenai = Senai.objects.all()
    context["dadosSenai"] = dadosSenai
    if request.method == 'POST':
        form = formCadastroUsuario(request.POST)
        if form.is_valid():
            var_nome = form.cleaned_data['first_name']
            var_sobrenome = form.cleaned_data['last_name']
            var_usuario = form.cleaned_data['user']
            var_email = form.cleaned_data['email']
            var_senha = form.cleaned_data['password']

            user = User.objects.create_user(username=var_usuario, email=var_email, password=var_senha)
            user.first_name = var_nome
            user.last_name = var_sobrenome
            user.save()
            return redirect('/login')
            print('Cadastro realizado com sucesso')
    else:
        form = formCadastroUsuario()
        context['form'] = form
        print('Cadastro falhou')
    return render(request, 'cadastroUsuario.html', context)

def login(request):
    context = {}
    dadosSenai = Senai.objects.all()
    context["dadosSenai"] = dadosSenai
    if request.method == 'POST':
        form = FormLogin(request.POST)
        if form.is_valid():

            var_usuario = form.cleaned_data['user']
            var_senha = form.cleaned_data['password']
            
            user = authenticate(username=var_usuario, password=var_senha)

            if user is not None:
                auth_login(request, user)
                return redirect('/welcomeHomepage')  
            else:
                print('Login falhou')
    else:
        form = FormLogin()
        context['form'] = form
        return render(request, 'login.html', context)
    

def buscar_itens(request):
    context = {}
    query = request.GET.get('q')  # Pega o valor digitado no campo de busca
    if query:
        inventario = Inventario.objects.filter(num_inventario__icontains=query)
    else:
        inventario = Inventario.objects.all()

    context['inventario'] = inventario
    form = InventarioForm()
    context['form'] = form
    
    return render(request, 'itens.html', context)

def excluir_inventario(request):
    if request.method == 'POST':
        num_inventario = request.POST.get('num_inventario')
        print(f"Recebido num_inventario: {num_inventario}")  # Verificando o valor recebido

        # Excluir o item baseado no número de inventário
        try:
            item = Inventario.objects.get(num_inventario=num_inventario)
            item.delete()
            print(f"Item {num_inventario} excluído com sucesso")  # Log de sucesso
            return redirect('itens')  # Redirecionar após exclusão
        except Inventario.DoesNotExist:
            print(f"Item {num_inventario} não encontrado")  # Log de erro
            return HttpResponse("Item não encontrado.", status=404)
    return HttpResponse("Método não permitido.", status=405)

#def excluir_sala(request):
    # if request.method == 'POST':
         

AppGDP/templates/cadastroUsuario.html
{% extends "index.html" %}
{% load static %}

{% block body %}
{% include "navbar.html" %}
<main class="bg-body-l-w">
    <form class="login-form" method="POST" action="{% url 'cadastroUsuario' %}">
        {% csrf_token %}
        <h1 class="titleLogin">Cadastro</h1>

        <div class="input-group ig1">
            <label for="id_first_name"><b>Nome</b></label>
            <div class="input-container">
                {{ form.first_name }}
            </div>
        </div>

        <div class="input-group ig1">
            <label for="id_last_name"><b>Sobrenome</b></label>
            <div class="input-container">
                {{ form.last_name }}
            </div>
        </div>

        <div class="input-group ig1">
            <label for="id_user"><b>Usuário</b></label>
            <div class="input-container">
                {{ form.user }}
            </div>
        </div>

        <div class="input-group ig1">
            <label for="id_email"><b>Email</b></label>
            <div class="input-container">
                {{ form.email }}
            </div>
        </div>

        <div class="input-group ig2">
            <label for="id_password"><b>Senha</b></label>
            <div class="input-container">
                {{ form.password }}
            </div>
        </div>

        <button type="submit" class="btn-login">Cadastrar</button>
    </form>
</main>
{% endblock %}

AppGDP/templates/faq.html
{% extends "index.html" %}
{% load static %}

{% block body %}

{% include "navbar.html" %}
{% include "vectorFormas.html" %}
<div class="accordion">
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            O que é o gerenciamento de patrimônios no SENAI?
        </div>
        <div class="accordion-item-desc">
            O gerenciamento de patrimônios no SENAI envolve a administração e o controle dos bens e ativos físicos da instituição. Isso inclui a identificação, registro, manutenção, e descarte adequado dos patrimônios para garantir sua conservação e utilização eficiente.
        </div>
    </div>
    
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            Como os patrimônios são identificados e registrados?
        </div>
        <div class="accordion-item-desc">
            Cada patrimônio do SENAI recebe uma etiqueta com um código único de identificação. Esse código é registrado em um sistema de gerenciamento, onde são armazenadas informações detalhadas sobre o bem, como data de aquisição, localização, valor, e condição atual.
        </div>
    </div>
    
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            Como é feita a manutenção dos patrimônios?
        </div>
        <div class="accordion-item-desc">
            A manutenção dos patrimônios no SENAI é realizada de forma preventiva e corretiva. Equipamentos e máquinas recebem manutenção regular para evitar falhas, e reparos são feitos sempre que necessário para garantir que os patrimônios permaneçam operacionais e em boas condições.
        </div>
    </div>
    
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            Qual é a importância do gerenciamento de patrimônios?
        </div>
        <div class="accordion-item-desc">
            Um gerenciamento eficaz de patrimônios garante que os recursos da instituição sejam utilizados de forma eficiente, reduzindo desperdícios e assegurando que todos os bens estejam em bom estado de conservação. Isso também facilita auditorias e relatórios financeiros precisos.
        </div>
    </div>
    
</div>

<script>
    function toggleAccordion(element) {
        const desc = element.nextElementSibling;
        const icon = element.querySelector('.icon');

        if (desc.style.maxHeight) {
            desc.style.maxHeight = null;
            desc.style.opacity = 0;
            icon.textContent = "+";
        } else {
            desc.style.maxHeight = desc.scrollHeight + "px";
            desc.style.opacity = 1;
            icon.textContent = "-";
        }
    }
</script>

{% endblock %}

AppGDP/templates/homepage.html
{% extends "index.html" %}
{% load static %}

{% block body %}

{% include "navbar.html" %}
{% include "vectorFormas.html" %}
<div class="itensHomepage">
    <div class="textsHomepage">
        <p class="subtitlesHomepage">Gerenciamento de patrimônios</p>
        <div id="svg-container">
            <h1 class="titleHomepage">Senai Admin</h1>
        </div>
        <p class="subtitlesHomepage2">Caso já tenha um usuário, faça login para acessar o site</p>
        <a href="login" class="TransparentBlackButton-component">Entrar</a>
            
        

    </div>
    
    <div class="iconHomepage">
        <img src="{% static 'img/ImageIcon.png' %}" alt="ImageIcon" class="ImageIcon-component">
    </div>
</div>  
{% endblock %}

AppGDP/templates/itens.html
{% extends "index.html" %}
{% load static %}

{% block body %}
{% include "navbar.html" %}

<main class="bg-body-i-w">
    <h1>Itens</h1>
    <h2>Sala - {{ item.sala }}</h2>

    <div class="search-container">
        <form id="searchForm" method="GET" action="{% url 'buscar_itens' %}">
            <div class="search-container">
                <button type="submit">
                    <span class="material-symbols-outlined" id="iconItens">search</span>
                </button>
                <input class="input-itens" type="text" name="q" id="searchInput"
                    placeholder="Buscar por número de inventário...">
            </div>
        </form>

        <button>
            <span class="material-symbols-outlined" id="iconItens">filter_list</span>
        </button>

        <button class="add-button" onclick="openModal('modalAddItem')">
            <span class="material-symbols-outlined" id="iconItens">add_circle</span>
            <p class="add-text">Adicionar</p>
        </button>
    </div>

    <div class="items-container">
        {% for item in inventario %}
        <div class="item-card"
            onclick="openItemModal('{{ item.denominacao }}', '{{ item.num_inventario }}', '{{ item.link_imagem }}', '{{ item.localizacao }}', '{{ item.sala }}')">
            <div class="bg-img">
                <img src="{{ item.link_imagem }}" alt="{{ item.denominacao }}">
            </div>
            <div class="inf">
                <h3>{{ item.denominacao }}</h3>
                <p>ID: {{ item.num_inventario }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Modal de Visualização do Item -->
    <div id="modalItem" class="modal">
        <div class="modal-content">
            <button type="button" class="btn-close" onclick="closeModal('modalItem')">X</button>
            <h2 class="adicionarH2Itens">Informações</h2>

            <form id="deleteItemForm" method="POST" action="{% url 'excluir_inventario' %}">
                {% csrf_token %}

                <label for="denominacaoInput">Denominação:</label>
                <input type="text" id="denominacaoInput" name="denominacao" value="" readonly>

                <label for="numInventarioInput">Número de Inventário:</label>
                <input type="text" id="numInventarioInput" name="numInventario" value="" readonly>

                <label for="localizacaoInput">Localização: </label>
                <input type="text" id="localizacaoInput" name="localizacao" value="" readonly>

                <label for="salaInput">Sala:</label>
                <input type="text" id="salaInput" name="sala" value="" readonly>

                <label for="imagemInput">Imagem:</label>
                <input type="text" id="imagemInput" name="imagem" value="" readonly>

                <input type="hidden" name="num_inventario" id="numInventarioExcluir" value="">

                <div class="modal-actions">
                    <button type="button" class="btn-edit" onclick="editarItem()">Editar</button>
                    <button type="button" class="btn-delete" onclick="openDeleteConfirmation()">Excluir</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Modal de Confirmação de Adição -->
    <div id="modalConfirmation" class="modal-confirmation">
        <div class="modal-content-confirmation">
            <h2>Item Adicionado!</h2>
            <p>O item foi adicionado com sucesso ao inventário.</p>
            <button class="btn-close-confirmation" onclick="closeConfirmation()">Fechar</button>
        </div>
    </div>

    <!-- Modal de Confirmação de Exclusão -->
    <div id="modalDeleteConfirmation" class="modal-confirmation">
        <div class="modal-content-confirmation">
            <h2>Confirmar Exclusão</h2>
            <p>Tem certeza que deseja excluir este item?</p>
            <div class="modal-actions">
                <button type="button" class="btn-close-confirmation" onclick="closeDeleteConfirmation()">Cancelar</button>
                <button type="button" class="btn-close-confirmation" onclick="submitDeleteForm()">Excluir</button>
            </div>
        </div>  
    </div>

    <div id="modalAddItem" class="modal">
        <div class="modal-content">
            <button type="button" class="btn-close" onclick="closeModal('modalAddItem')">X</button>
            <h2 class="adicionarH2Itens">Adicionar Item</h2>
            <form id="addItemForm" method="POST" action="{% url 'adicionar_inventario' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="modal-actions">
                    <button type="submit" class="btn-add">Adicionar</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        function openItemModal(denominacao, numInventario, linkImagem, localizacao, sala) {
            document.getElementById('denominacaoInput').value = denominacao;
            document.getElementById('numInventarioInput').value = numInventario;
            document.getElementById('imagemInput').value = linkImagem;
            document.getElementById('localizacaoInput').value = localizacao;
            document.getElementById('salaInput').value = sala;

            // Definir o valor do num_inventario no campo oculto de exclusão
            document.getElementById('numInventarioExcluir').value = numInventario;

            openModal('modalItem');
        }

        function openModal(modalId) {
            document.getElementById(modalId).style.display = 'block';
        }

        function closeModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
        }

        function openDeleteConfirmation() {
            document.getElementById('modalDeleteConfirmation').style.display = 'block';
        }

        function closeDeleteConfirmation() {
            document.getElementById('modalDeleteConfirmation').style.display = 'none';
        }

        function submitDeleteForm() {
            document.getElementById('deleteItemForm').submit();
        }

        window.onclick = function (event) {
            if (event.target.classList.contains('modal')) {
                event.target.style.display = "none";
            }
        }

        function openConfirmation() {
            document.getElementById('modalConfirmation').style.display = 'block';
        }

        function closeConfirmation() {
            document.getElementById('modalConfirmation').style.display = 'none';
            window.location.href = "{% url 'itens' %}";
        }

        document.getElementById('addItemForm').addEventListener('submit', function (event) {
            event.preventDefault();
            const formData = new FormData(this);

            fetch("{% url 'adicionar_inventario' %}", {
                method: 'POST',
                body: formData,
            })
                .then(response => {
                    if (response.ok) {
                        closeModal('modalAddItem');
                        openConfirmation();
                    } else {
                        alert("Erro ao adicionar o item.");
                    }
                })
                .catch(error => {
                    console.error("Erro:", error);
                });
        });
    </script>

</main>
{% endblock %}

AppGDP/templates/login.html
{% extends "index.html" %}
{% load static %}

{% block body %}
{% include "navbar.html" %}
{% include "vectorFormas.html" %}
<main class="bg-body-l-w">
    <form class="login-form" method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        <h1 class="titleLogin">Login</h1>

        <div class="input-group ig1">
            <label for="id_user"><b>Usuário</b></label>
            <div class="input-container">
                {{ form.user }}
            </div>
        </div>

        <div class="input-group ig2">
            <label for="id_password"><b>Senha</b></label>
            <div class="input-container">
                {{ form.password }}

            </div>
        </div>

        <button type="submit" class="btn-login">Entrar</button>

        <p style="font-family: poppins; margin-top: 10px;">Caso não tenha cadastro, <a href="{% url 'cadastroUsuario' %}" style="text-decoration: none;">cadastre-se aqui</a></p>
    </form>
</main>
{% endblock %}

AppGDP/templates/profile.html
{% extends "index.html" %}
{% load static %}

{% block body %}

{% include "navbar.html" %}
<div class="Profile-Body">
    <div class="container-profile">
        <img src="{% static 'img/ProfileAvatar.png' %}" alt="Avatar" class="Avatar">

        <div class="sub-container-profile">
            <div class="profile-item">
                <label for="email">Email</label>
                <input type="text" id="email" value="ga375464@gmail.com" disabled>
                <div class="edit-icon">
                    <svg width="60" height="61" viewBox="0 0 60 61" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect y="0.5" width="60" height="60" rx="30" fill="#B01818" />
                        <path
                            d="M17.1667 43.7222H19.7792L37.7 25.2583L35.0875 22.5667L17.1667 41.0306V43.7222ZM13.5 47.5V39.4722L37.7 14.5861C38.0667 14.2398 38.4715 13.9722 38.9146 13.7833C39.3576 13.5944 39.8236 13.5 40.3125 13.5C40.8014 13.5 41.275 13.5944 41.7333 13.7833C42.1917 13.9722 42.5889 14.2556 42.925 14.6333L45.4458 17.2778C45.8125 17.6241 46.0799 18.0333 46.2479 18.5056C46.416 18.9778 46.5 19.45 46.5 19.9222C46.5 20.4259 46.416 20.906 46.2479 21.3625C46.0799 21.819 45.8125 22.2361 45.4458 22.6139L21.2917 47.5H13.5ZM36.3708 23.9361L35.0875 22.5667L37.7 25.2583L36.3708 23.9361Z"
                            fill="#E8EAED" />
                    </svg>
                </div>
            </div>

            <div class="profile-item">
                <label for="nome">Nome</label>
                <input type="text" id="nome" value="Guilherme Augusto" disabled>
                <div class="edit-icon">
                    <svg width="60" height="61" viewBox="0 0 60 61" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect y="0.5" width="60" height="60" rx="30" fill="#B01818" />
                        <path
                            d="M17.1667 43.7222H19.7792L37.7 25.2583L35.0875 22.5667L17.1667 41.0306V43.7222ZM13.5 47.5V39.4722L37.7 14.5861C38.0667 14.2398 38.4715 13.9722 38.9146 13.7833C39.3576 13.5944 39.8236 13.5 40.3125 13.5C40.8014 13.5 41.275 13.5944 41.7333 13.7833C42.1917 13.9722 42.5889 14.2556 42.925 14.6333L45.4458 17.2778C45.8125 17.6241 46.0799 18.0333 46.2479 18.5056C46.416 18.9778 46.5 19.45 46.5 19.9222C46.5 20.4259 46.416 20.906 46.2479 21.3625C46.0799 21.819 45.8125 22.2361 45.4458 22.6139L21.2917 47.5H13.5ZM36.3708 23.9361L35.0875 22.5667L37.7 25.2583L36.3708 23.9361Z"
                            fill="#E8EAED" />
                    </svg>
                </div>
            </div>

            <div class="profile-item">
                <label for="id">ID</label>
                <input type="text" id="id" value="85236" disabled>
            </div>

            <div class="profile-item">
                <label for="sala">Sala</label>
                <input type="text" id="sala" value="C13" disabled>
            </div>

            <div class="profile-item">
                <label for="senha">Senha</label>
                <input type="password" id="senha" value="********" disabled class="password">
            </div>
        </div>
    </div>

</div>
{% endblock %}

AppGDP/templates/welcomeHomepage.html
{% extends "index.html" %}
{% load static %}

{% block body %}

{% include "navbar.html" %}
<div class="body-homepage">
    <header class="cabecalho-welcome">
        <div class="conteudo-cabecalho">
            <h1>Bem-vindo ao <span class="destaque"> <br> Patrimônios </span> & <span class="destaque">Ordem</span></h1>
            <p>Sua solução definitiva para gerenciar patrimônios de maneira eficiente e organizada.</p>
            <button class="botao-cadastro">Cadastre-se</button>
        </div>
        <div class="imagem-cabecalho">
            <div class="carousel-container">
                <img src="{% static 'img/img1.png' %}" alt="Imagem 1">
            </div>
        </div>
    </header>

    <section class="servicos">
        <h2>Serviços</h2>
        <div class="container-servicos">
            <div class="cartao-servico">
                <div class="div-cartao">
                    <span class="material-symbols-outlined"> edit_note </span>
                    <h3>Editar e Mover Patrimônios</h3>
                    <p>Soluções eficientes para controlar e monitorar seus ativos.</p>
                </div>
                <button class="button-view">
                    Ver
                </button>
            </div>
            <div class="cartao-servico">
                <div class="div-cartao">
                    <span class="material-symbols-outlined"> engineering </span>
                    <h3>Adicionar a lista de manutenção do patrimônio</h3>
                    <p>Proteção máxima para o seu patrimônio com tecnologia de ponta.</p>
                </div>
                <button class="button-view">
                    Ver
                </button>
            </div>
            <div class="cartao-servico">
                <div class="div-cartao">
                    <span class="material-symbols-outlined"> flaky </span>
                    <h3>Adicionar & Excluir um patrimônio</h3>
                    <p>Relatórios completos para a melhor tomada de decisões.</p>
                </div>
                <button class="button-view">
                    Ver
                </button>
            </div>
            <div class="cartao-servico">
                <div class="div-cartao">
                    <span class="material-symbols-outlined"> data_table </span>
                    <h3>Ver Tabela de Patrimônios</h3>
                    <p>Assistência contínua para garantir a tranquilidade da sua operação.</p>
                </div>
                <button class="button-view">
                    Ver
                </button>
            </div>
        </div>
    </section>

    <section>
        <div class="Salas">
            <div class="Salas-text">
                <p>Vá para esta página</p>
                <p>Salas</p>
                <p>Salas mais utilizadas do Senai!</p>
            </div>
            <div class="botoes-salas">
                <div class="botao-sala">
                    <span class="material-symbols-outlined">
                        edit
                        </span>
                </div>
                <div class="botao-sala">
                    <span class="material-symbols-outlined">
                        add_circle
                        </span>
                </div>
                <div class="botao-sala">
                    <span class="material-symbols-outlined">
                        delete
                        </span>
                </div>
            </div>
        </div>
    </section>
    <section class="grid-container">
        <div class="item-card-w">
            <div class="image-container">
                <img src="{% static 'img/salaImage.png' %}" alt="Notebook Dell 80GB">
                <span class="badge">40</span>
            </div>
            <div class="item-info">
                <h3>Sala C13</h3>
                <p>1260689</p>
                <p>Notebook de Número 15</p>
                <p>Localizado na C13</p>
            </div>
        </div> 
        <div class="item-card-w">
            <div class="image-container">
                <img src="{% static 'img/salaImage.png' %}" alt="Notebook Dell 80GB">
                <span class="badge">40</span>
            </div>
            <div class="item-info">
                <h3>Sala C14</h3>
                <p>1260689</p>
                <p>Notebook de Número 15</p>
                <p>Localizado na C14</p>
            </div>
        </div>
        <!-- ---------------------- -->
        <div class="item-card-w">
            <div class="image-container">
                <img src="{% static 'img/salaImage.png' %}" alt="Notebook Dell 80GB">
                <span class="badge">40</span>
            </div>
            <div class="item-info">
                <h3>Sala C15</h3>
                <p>1260689</p>
                <p>Notebook de Número 15</p>
                <p>Localizado na C15</p>
            </div>
        </div>
        <!-- ---------------------- -->
        <div class="item-card-w">
            <div class="image-container">
                <img src="{% static 'img/salaImage.png' %}" alt="Notebook Dell 80GB">
                <span class="badge">40</span>
            </div>
            <div class="item-info">
                <h3>Sala C16</h3>
                <p>1260689</p>
                <p>Notebook de Número 15</p>
                <p>Localizado na C16</p>
            </div>
        </div>
        <!-- ---------------------- -->
        <div class="item-card-w">
            <div class="image-container">
                <img src="{% static 'img/salaImage.png' %}" alt="Notebook Dell 80GB">
                <span class="badge">40</span>
            </div>
            <div class="item-info">
                <h3>Sala C17</h3>
                <p>1260689</p>
                <p>Notebook de Número 15</p>
                <p>Localizado na C17</p>
            </div>
        </div>
        <!-- ---------------------- -->
        <div class="item-card-w">
            <div class="image-container">
                <img src="{% static 'img/salaImage.png' %}" alt="Notebook Dell 80GB">
                <span class="badge">40</span>
            </div>
            <div class="item-info">
                <h3>Sala C18</h3>
                <p>1260689</p>
                <p>Notebook de Número 15</p>
                <p>Localizado na C18</p>
            </div>
        </div>
    </section>
</div>

{% endblock %}

templates/vectorFormas.html
{% load static %}

<img src="{% static 'img/Formas.png' %}" alt="Vetor de formas" class="vetorFormas-Component">